name: Build Android App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil Kodingan
    - uses: actions/checkout@v4

    # 2. [BARU] Buat file .env dari Secret
    # Ini solusi error "No file or variants found for asset: .env"
    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    # 3. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # 4. Setup Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # 5. Install Dependencies
    - name: Install Dependencies
      run: flutter pub get

    # 6. Decode Keystore
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

    # 7. Build APK Release
    - name: Build APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: flutter build apk --release

    # 8. Build App Bundle
    - name: Build App Bundle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: flutter build appbundle --release

    # 9. Upload APK
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # 10. Upload AAB
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab